# Generated by Django 2.1.2 on 2018-10-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=50)),
                ('valor_atributo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Img_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_img', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('desc_producto', models.CharField(max_length=500)),
                ('id_estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Productos')),
            ],
        ),
        migrations.AddField(
            model_name='img_producto',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Productos'),
        ),
        migrations.AddField(
            model_name='atributos',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Productos'),
        ),
    ]
