# Generated by Django 2.1.2 on 2018-10-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20181020_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='desc_producto',
            field=models.TextField(),
        ),
    ]
