# Generated by Django 2.1.2 on 2018-10-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20181020_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_producto',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
