# Generated by Django 2.1.2 on 2018-10-21 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20181020_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos_Relacionados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto', to='inventario.Productos')),
                ('id_producto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod_relacionado', to='inventario.Productos')),
            ],
        ),
    ]
