# Generated by Django 2.1.2 on 2018-10-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_productos_relacionados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=12)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Productos')),
            ],
        ),
    ]
