# Generated by Django 2.1.2 on 2018-10-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20181023_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_compras',
            name='session',
            field=models.CharField(max_length=18),
        ),
    ]
