# Generated by Django 2.1.2 on 2018-10-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20181028_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion_envio',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='direccion_envio',
            name='id_municipio',
        ),
        migrations.RemoveField(
            model_name='direccion_envio',
            name='id_pais',
        ),
        migrations.AddField(
            model_name='direccion_envio',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='direccion_envio',
            name='municipio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='direccion_envio',
            name='pais',
            field=models.CharField(default='', max_length=50),
        ),
    ]
