# Generated by Django 2.1.2 on 2018-10-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20181028_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion_envio',
            name='referencia',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
