# Generated by Django 2.1.2 on 2018-12-02 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_auto_20181201_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 10, 14, 26, 443786)),
        ),
    ]
