# Generated by Django 2.1.2 on 2019-02-21 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_auto_20190213_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.Estatus'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 7, 57, 32, 450325)),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_proveedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='inventario.Proveedor'),
        ),
    ]
