# Generated by Django 2.1.2 on 2019-02-22 02:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_auto_20190221_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_proveedor',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Proveedor'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 20, 36, 9, 404385)),
        ),
    ]
