# Generated by Django 2.1.2 on 2019-02-23 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_auto_20190221_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 3, 1, 54, 744807)),
        ),
    ]
