# Generated by Django 2.1.2 on 2019-02-26 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_auto_20190223_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 20, 21, 24, 817181)),
        ),
        migrations.AlterUniqueTogether(
            name='productos_relacionados',
            unique_together={('id_producto', 'id_producto_relacionado')},
        ),
    ]
