# Generated by Django 2.1.2 on 2019-02-26 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_auto_20190225_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 21, 14, 55, 659337)),
        ),
    ]
