# Generated by Django 2.1.2 on 2019-02-28 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_auto_20190227_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='clave_prod_proveedor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 22, 9, 43, 209647)),
        ),
        migrations.AlterUniqueTogether(
            name='categorias',
            unique_together={('categoria',)},
        ),
        migrations.AlterUniqueTogether(
            name='rel_producto_categoria',
            unique_together={('id_producto', 'id_categoria')},
        ),
    ]
