# Generated by Django 2.1.2 on 2019-02-28 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_auto_20190227_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallas',
            name='entrada',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tallas',
            name='salida',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 22, 18, 22, 38570)),
        ),
    ]
