# Generated by Django 2.1.2 on 2019-02-28 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_auto_20190227_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallas',
            name='entrada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tallas',
            name='salida',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 0, 58, 10, 558666)),
        ),
    ]
