# Generated by Django 2.1.2 on 2019-03-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_auto_20190228_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='talla',
        ),
        migrations.RemoveField(
            model_name='direccion_envio_venta',
            name='id_venta',
        ),
        migrations.DeleteModel(
            name='Detalle_Venta',
        ),
        migrations.DeleteModel(
            name='Direccion_Envio_Venta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
