# Generated by Django 2.1.2 on 2019-03-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_auto_20190228_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito_compras',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='carrito_compras',
            name='talla',
        ),
        migrations.DeleteModel(
            name='Carrito_Compras',
        ),
    ]
