# Generated by Django 2.1.2 on 2019-03-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_auto_20190228_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direccion_Envio',
        ),
        migrations.AlterUniqueTogether(
            name='img_producto',
            unique_together={('id_producto', 'orden')},
        ),
    ]
