# Generated by Django 2.2.6 on 2020-01-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_auto_20190301_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio_proveedor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=26),
        ),
    ]
