# Generated by Django 2.2.6 on 2020-01-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_productos_precio_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_producto',
            name='nom_img',
            field=models.CharField(max_length=7),
        ),
    ]
