# Generated by Django 2.2.6 on 2020-01-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_auto_20200117_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Proveedor'),
        ),
    ]
