# Generated by Django 2.2.6 on 2020-01-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0039_productos_publicado_ml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus_publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=20)),
            ],
        ),
    ]
