# Generated by Django 2.2.6 on 2020-01-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0042_auto_20200125_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='publicado_ml',
        ),
    ]
