# Generated by Django 2.2.6 on 2020-01-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0044_delete_estatus_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='publicad_ml',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='publicado_ml', to='inventario.Estatus'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='id_estatus', to='inventario.Estatus'),
        ),
    ]
