# Generated by Django 2.2.6 on 2020-02-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0047_auto_20200126_0022'),
    ]

    
