# Generated by Django 2.2.6 on 2020-02-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0048_auto_20200219_1421'),
    ]

