# Generated by Django 2.2.6 on 2020-02-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0049_auto_20200219_1514'),
    ]

   
