# Generated by Django 2.2.6 on 2020-02-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0050_auto_20200219_1516'),
    ]

    
