# Generated by Django 2.1.2 on 2019-03-01 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20190228_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion_Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('cp', models.CharField(max_length=10)),
                ('municipio', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='', max_length=50)),
                ('pais', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 0, 15, 34, 79684)),
        ),
    ]
