# Generated by Django 2.1.2 on 2019-03-01 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20190301_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_venta', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 1, 2, 26, 12, 29989)),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_estatus_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ventas.Estatus_Venta'),
        ),
    ]
