# Generated by Django 2.1.2 on 2019-03-03 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20190301_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='link_seguimiento',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 13, 22, 25, 560826)),
        ),
    ]
