# Generated by Django 2.1.2 on 2019-03-03 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20190303_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 13, 35, 50, 45669)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='link_seguimiento',
            field=models.CharField(default='No Registrado', max_length=200, null=True),
        ),
    ]
