# Generated by Django 2.1.2 on 2019-03-05 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_auto_20190304_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 23, 29, 17, 723668)),
        ),
    ]
