# Generated by Django 2.1.2 on 2019-03-09 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_auto_20190309_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 10, 40, 43, 435868)),
        ),
    ]
