# Generated by Django 2.1.2 on 2019-04-06 06:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0016_auto_20190315_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion_envio_venta',
            name='cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 0, 15, 25, 590843)),
        ),
    ]
