# Generated by Django 2.1.2 on 2019-04-12 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_auto_20190408_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 8, 24, 30, 846261)),
        ),
    ]
