# Generated by Django 2.1.2 on 2019-05-26 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0025_auto_20190525_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 2, 12, 6, 138029)),
        ),
    ]
