# Generated by Django 2.1.2 on 2019-05-26 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0026_auto_20190526_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion_envio',
            name='numero',
        ),
        migrations.AddField(
            model_name='direccion_envio',
            name='numero_exterior',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='direccion_envio',
            name='numero_interior',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 18, 8, 16, 97299)),
        ),
    ]
