# Generated by Django 2.1.2 on 2019-05-27 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_auto_20190526_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direccion_Envio',
        ),
        migrations.RemoveField(
            model_name='direccion_envio_venta',
            name='numero',
        ),
        migrations.AddField(
            model_name='direccion_envio_venta',
            name='numero_exterior',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='direccion_envio_venta',
            name='numero_interior',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 19, 5, 51, 393213)),
        ),
    ]
