# Generated by Django 2.1.2 on 2019-06-02 05:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_auto_20190526_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='seguridad.Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 0, 34, 55, 416006)),
        ),
    ]
