# Generated by Django 2.1.2 on 2019-06-02 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_auto_20190602_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 10, 25, 2, 494702)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='link_seguimiento',
            field=models.CharField(default='No Disponible', max_length=200, null=True),
        ),
    ]
