# Generated by Django 2.1.2 on 2019-06-20 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_auto_20190602_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 23, 52, 21, 781020)),
        ),
    ]
