# Generated by Django 2.2.4 on 2019-09-16 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0033_auto_20190623_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 15, 45, 6, 49119)),
        ),
    ]
