# Generated by Django 2.2.4 on 2019-10-25 03:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0034_auto_20190916_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 3, 45, 55, 688056, tzinfo=utc)),
        ),
    ]
