# Generated by Django 2.2.6 on 2019-11-01 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0035_auto_20191024_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 19, 35, 54, 431990, tzinfo=utc)),
        ),
    ]
