# Generated by Django 2.2.6 on 2019-11-13 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0036_auto_20191101_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 6, 53, 21, 502873, tzinfo=utc)),
        ),
    ]
