# Generated by Django 2.2.6 on 2019-11-13 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0037_auto_20191113_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 19, 3, 16, 407836, tzinfo=utc)),
        ),
    ]
