# Generated by Django 2.2.6 on 2019-11-14 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0038_auto_20191113_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 3, 30, 3, 845775, tzinfo=utc)),
        ),
    ]
