# Generated by Django 2.2.6 on 2019-11-14 03:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0039_auto_20191113_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion_envio_venta',
            name='apellido_m',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 3, 44, 9, 538297, tzinfo=utc)),
        ),
    ]
