# Generated by Django 2.2.6 on 2020-01-12 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0041_auto_20191126_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 21, 9, 35, 358826, tzinfo=utc)),
        ),
    ]
