# Generated by Django 2.2.6 on 2020-01-12 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0042_auto_20200112_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 22, 10, 24, 240647, tzinfo=utc)),
        ),
    ]
