# Generated by Django 2.2.6 on 2020-01-12 23:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0043_auto_20200112_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 23, 19, 17, 670562, tzinfo=utc)),
        ),
    ]
