# Generated by Django 2.2.6 on 2020-01-13 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0047_auto_20200112_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 1, 24, 12, 647661, tzinfo=utc)),
        ),
    ]
