# Generated by Django 2.2.6 on 2020-01-13 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0048_auto_20200112_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 7, 49, 19, 31239, tzinfo=utc)),
        ),
    ]
