# Generated by Django 2.2.6 on 2020-01-15 04:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0050_auto_20200114_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_medio_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.Medio_Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 4, 34, 13, 812916, tzinfo=utc)),
        ),
    ]
