# Generated by Django 2.2.6 on 2020-01-15 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0052_auto_20200115_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 9, 29, 17, 830685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_medio_venta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ventas.Medio_Venta'),
            preserve_default=False,
        ),
    ]
