# Generated by Django 2.2.6 on 2020-01-15 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0060_auto_20200115_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 20, 24, 15, 557, tzinfo=utc)),
        ),
    ]
