# Generated by Django 2.2.6 on 2020-01-16 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0062_auto_20200115_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 20, 51, 6, 424203, tzinfo=utc)),
        ),
    ]
