# Generated by Django 2.2.6 on 2020-01-17 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0063_auto_20200116_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 7, 37, 45, 27483, tzinfo=utc)),
        ),
    ]
