# Generated by Django 2.2.6 on 2020-01-17 09:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0071_auto_20200117_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Tallas'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 9, 58, 29, 981889, tzinfo=utc)),
        ),
    ]
