# Generated by Django 2.2.6 on 2020-01-17 19:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0072_auto_20200117_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Productos'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='talla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.Tallas'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 19, 57, 25, 699614, tzinfo=utc)),
        ),
    ]
