# Generated by Django 2.2.6 on 2020-01-17 21:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0074_auto_20200117_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 21, 25, 56, 508041, tzinfo=utc)),
        ),
    ]
