# Generated by Django 2.2.6 on 2020-01-17 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0076_auto_20200117_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='seguridad.Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 21, 29, 9, 8550, tzinfo=utc)),
        ),
    ]
