# Generated by Django 2.2.6 on 2020-01-19 03:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0080_auto_20200117_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 3, 57, 52, 553275, tzinfo=utc)),
        ),
    ]
