# Generated by Django 2.2.6 on 2020-01-19 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0082_auto_20200119_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 15, 23, 19, 12602, tzinfo=utc)),
        ),
    ]
