# Generated by Django 2.2.6 on 2020-01-19 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0083_auto_20200119_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 15, 26, 26, 658803, tzinfo=utc)),
        ),
    ]
