# Generated by Django 2.2.6 on 2020-01-20 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0084_auto_20200119_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 20, 7, 37, 824268, tzinfo=utc)),
        ),
    ]
