# Generated by Django 2.2.6 on 2020-01-25 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0085_auto_20200120_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 8, 5, 12, 206616, tzinfo=utc)),
        ),
    ]
