# Generated by Django 2.2.6 on 2020-01-26 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0086_auto_20200125_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 3, 0, 43, 442009, tzinfo=utc)),
        ),
    ]
