# Generated by Django 2.2.6 on 2020-01-26 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0092_auto_20200125_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 4, 29, 1, 979373, tzinfo=utc)),
        ),
    ]
