# Generated by Django 2.2.6 on 2020-01-28 04:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0099_auto_20200126_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 4, 51, 37, 962039, tzinfo=utc)),
        ),
    ]
