# Generated by Django 2.2.6 on 2020-01-28 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0100_auto_20200127_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 5, 4, 36, 593156, tzinfo=utc)),
        ),
    ]
