# Generated by Django 2.2.6 on 2020-01-28 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0101_auto_20200127_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 21, 7, 8, 99098, tzinfo=utc)),
        ),
    ]
