# Generated by Django 2.2.6 on 2020-01-28 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0106_auto_20200128_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 21, 18, 28, 883123, tzinfo=utc)),
        ),
    ]
