# Generated by Django 2.2.6 on 2020-02-04 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0110_auto_20200128_1534'),
    ]

   