# Generated by Django 2.2.6 on 2020-02-19 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0111_auto_20200204_1422'),
    ]

  