# Generated by Django 2.2.6 on 2020-02-19 06:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0112_auto_20200219_0019'),
    ]

    
