# Generated by Django 2.2.6 on 2020-03-12 05:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0115_auto_20200219_1434'),
    ]

   