# Generated by Django 2.2.6 on 2020-03-12 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0120_auto_20200311_2318'),
    ]

    