# Generated by Django 2.2.6 on 2020-03-12 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0051_auto_20200219_2330'),
        ('ventas', '0123_auto_20200311_2339'),
    ]

   
