# Generated by Django 2.2.6 on 2020-03-12 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0125_auto_20200312_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_forma_pago', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 7, 12, 31, 408244, tzinfo=utc)),
        ),
    ]
