# Generated by Django 2.2.6 on 2020-03-12 07:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0126_auto_20200312_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ventas.Forma_Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 7, 19, 9, 725575, tzinfo=utc)),
        ),
    ]
