# Generated by Django 2.2.6 on 2020-03-12 07:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0127_auto_20200312_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 7, 28, 12, 381482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.Forma_Pago'),
        ),
    ]
