# Generated by Django 2.2.6 on 2020-03-19 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0129_auto_20200319_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus_Envio_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_estatus_envio', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 6, 30, 27, 514912, tzinfo=utc)),
        ),
    ]
