# Generated by Django 2.2.6 on 2020-03-19 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0131_auto_20200319_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estatus_envio_producto',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.Estatus_Envio_Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 6, 37, 37, 450188, tzinfo=utc)),
        ),
    ]
