# Generated by Django 2.2.6 on 2020-04-02 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0132_auto_20200319_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Cupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 4, 6, 14, 285865, tzinfo=utc)),
        ),
    ]
