# Generated by Django 2.2.6 on 2020-04-03 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0134_auto_20200402_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=18)),
                ('folio_cupon', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 6, 13, 20, 712091, tzinfo=utc)),
        ),
    ]
