# Generated by Django 2.2.6 on 2020-04-03 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0135_auto_20200403_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_cupon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 7, 29, 40, 334617, tzinfo=utc)),
        ),
    ]
