# Generated by Django 2.2.6 on 2020-04-03 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0136_auto_20200403_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 8, 5, 21, 899196, tzinfo=utc)),
        ),
    ]
