# Generated by Django 2.2.6 on 2020-04-03 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0137_auto_20200403_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descuento_cupon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 18, 34, 1, 183848, tzinfo=utc)),
        ),
    ]
