# Generated by Django 2.2.6 on 2020-04-05 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0138_auto_20200403_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='folio_descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 8, 7, 45, 509330, tzinfo=utc)),
        ),
    ]
