# Generated by Django 2.2.6 on 2020-04-15 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0139_auto_20200405_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_compras',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 17, 50, 21, 146989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 17, 50, 21, 157089, tzinfo=utc)),
        ),
    ]
