# Generated by Django 2.2.6 on 2020-04-16 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0140_auto_20200415_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_compras',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 19, 25, 11, 827843, tzinfo=utc)),
        ),
    ]
