# Generated by Django 2.2.6 on 2020-06-17 04:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=50, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('colonia', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('pais', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('naturaleza', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Perfil')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Sucursal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Control_Folios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Sucursal')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Tipo_Movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=7)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 6, 17, 4, 18, 25, 729491, tzinfo=utc))),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('caja', models.CharField(max_length=1)),
                ('real_tarjeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('real_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('teorico_tarjeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('teorico_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Sucursal')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Tipo_Movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
