# Generated by Django 2.2.6 on 2020-06-17 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0002_auto_20200616_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 17, 9, 27, 273950, tzinfo=utc)),
        ),
    ]
