# Generated by Django 2.2.6 on 2020-06-17 22:25

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0005_auto_20200617_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajas',
            name='fecha_cierre',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 22, 25, 46, 221010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
