# Generated by Django 2.2.6 on 2020-06-17 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0006_auto_20200617_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 22, 30, 51, 547785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='folio',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
