# Generated by Django 2.2.6 on 2020-06-17 23:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0007_auto_20200617_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 23, 30, 50, 80605, tzinfo=utc)),
        ),
    ]
