# Generated by Django 2.2.6 on 2020-06-18 05:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0009_auto_20200618_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='otros_ingresos',
            name='comentario',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 5, 56, 42, 474017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 5, 56, 42, 484131, tzinfo=utc)),
        ),
    ]
