# Generated by Django 2.2.6 on 2020-06-18 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0011_auto_20200618_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 16, 51, 18, 863783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 16, 51, 18, 871789, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='comentario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 16, 51, 18, 871789, tzinfo=utc)),
        ),
    ]
