# Generated by Django 2.2.6 on 2020-06-18 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0013_auto_20200618_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 17, 17, 40, 801526, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 17, 17, 40, 802527, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 17, 17, 40, 804527, tzinfo=utc)),
        ),
    ]
