# Generated by Django 2.2.6 on 2020-06-22 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0019_auto_20200621_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajas',
            name='token_cierre_caja',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 1, 16, 20, 197929)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 1, 16, 20, 199932)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 1, 16, 20, 204931)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 1, 16, 20, 207932)),
        ),
        migrations.DeleteModel(
            name='Aux_Cierra_Caja',
        ),
    ]
