# Generated by Django 2.2.6 on 2020-06-22 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0021_auto_20200622_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='centavos_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='centavos_50',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 21, 47, 13, 559609)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='pesos_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='pesos_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='pesos_100',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='pesos_1000',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='pesos_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='pesos_20',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='pesos_200',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='pesos_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='pesos_50',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='pesos_500',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 21, 47, 13, 561672)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 21, 47, 13, 561672)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 21, 47, 13, 571277)),
        ),
    ]
