# Generated by Django 2.2.6 on 2020-06-25 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0022_auto_20200622_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajas',
            name='comentario',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 14, 48, 319150)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 14, 48, 322151)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 14, 48, 323152)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 14, 48, 325152)),
        ),
    ]
