# Generated by Django 2.2.6 on 2020-06-25 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0023_auto_20200625_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='comentario',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 17, 3, 878376)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 17, 3, 881376)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 17, 3, 883376)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 17, 3, 885377)),
        ),
    ]
