# Generated by Django 2.2.6 on 2020-06-26 00:43

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0024_auto_20200625_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='diferencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 0, 43, 26, 89948)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='importe',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='real_efectivo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='real_tarjeta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='teorico_efectivo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='teorico_tarjeta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 0, 43, 26, 96539)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='importe',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 0, 43, 26, 96539)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='importe',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 0, 43, 26, 101635)),
        ),
    ]
