# Generated by Django 2.2.6 on 2020-06-26 19:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empenos', '0025_auto_20200626_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajas',
            name='user_cierra_caja',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, related_name='user_cierra_caja', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 19, 34, 52, 680947)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 19, 34, 52, 685993)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 19, 34, 52, 685993)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 19, 34, 52, 685993)),
        ),
    ]
