# Generated by Django 2.2.6 on 2020-06-26 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0032_auto_20200626_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajas',
            name='estatus_guardado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 22, 29, 53, 660259)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 22, 29, 53, 663260)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 22, 29, 53, 665263)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 22, 29, 53, 668261)),
        ),
    ]
