# Generated by Django 2.2.6 on 2020-07-01 02:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0016_session'),
        ('empenos', '0033_auto_20200626_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costo_Kilataje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(max_length=10)),
                ('kilataje', models.CharField(max_length=10)),
                ('avaluo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empenos_Temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaluo', models.IntegerField()),
                ('mutuo_sugerido', models.IntegerField()),
                ('mutuo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 2, 28, 56, 657392)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 2, 28, 56, 657392)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 2, 28, 56, 657392)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 2, 28, 56, 665393)),
        ),
        migrations.CreateModel(
            name='Sub_Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_linea', models.CharField(max_length=100)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Linea')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('sub_linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Sub_Linea')),
            ],
        ),
        migrations.AddField(
            model_name='linea',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Tipo_Producto'),
        ),
        migrations.CreateModel(
            name='Joyeria_Empenos_Temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField()),
                ('empeno_temporal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Empenos_Temporal')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Costo_Kilataje')),
            ],
        ),
        migrations.AddField(
            model_name='empenos_temporal',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Marca'),
        ),
        migrations.AddField(
            model_name='empenos_temporal',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguridad.Session'),
        ),
    ]
