# Generated by Django 2.2.6 on 2020-07-01 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0034_auto_20200701_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_producto',
            old_name='Tipo_Producto',
            new_name='tipo_producto',
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 12, 53, 21, 293864)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 12, 53, 21, 297865)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 12, 53, 21, 299863)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 12, 53, 21, 303864)),
        ),
    ]
