# Generated by Django 2.2.6 on 2020-07-01 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0035_auto_20200701_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='sub_linea',
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 19, 49, 39, 420400)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 19, 49, 39, 422400)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 19, 49, 39, 426400)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 19, 49, 39, 428400)),
        ),
    ]
