# Generated by Django 2.2.6 on 2020-07-01 21:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0037_auto_20200701_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costo_kilataje',
            name='metal',
        ),
        migrations.AddField(
            model_name='costo_kilataje',
            name='tipo_producto',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='empenos.Tipo_Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 21, 47, 35, 244687)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 21, 47, 35, 247691)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 21, 47, 35, 249691)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 21, 47, 35, 253688)),
        ),
    ]
