# Generated by Django 2.2.6 on 2020-07-03 01:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empenos', '0039_auto_20200703_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joyeria_empenos_temporal',
            old_name='metal',
            new_name='costo_kilataje',
        ),
        migrations.RemoveField(
            model_name='empenos_temporal',
            name='session',
        ),
        migrations.AddField(
            model_name='empenos_temporal',
            name='linea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empenos.Linea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empenos_temporal',
            name='sub_linea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empenos.Sub_Linea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empenos_temporal',
            name='tipo_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empenos.Tipo_Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empenos_temporal',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 1, 8, 32, 662650)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 1, 8, 32, 667651)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 1, 8, 32, 669652)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 1, 8, 32, 672652)),
        ),
    ]
