# Generated by Django 2.2.6 on 2020-07-03 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0040_auto_20200703_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 12, 57, 10, 157451)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 12, 57, 10, 162454)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 12, 57, 10, 165453)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 12, 57, 10, 171458)),
        ),
        migrations.AlterUniqueTogether(
            name='joyeria_empenos_temporal',
            unique_together={('empeno_temporal',)},
        ),
    ]
