# Generated by Django 2.2.6 on 2020-07-05 02:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empenos', '0043_auto_20200703_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta_Empeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(max_length=7)),
                ('avaluo', models.IntegerField()),
                ('mutuo', models.IntegerField()),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 7, 5, 2, 34, 23, 681569))),
                ('fecha_vencimiento', models.DateTimeField()),
                ('nombre_cotitular', models.CharField(max_length=20)),
                ('apellido_p_cotitular', models.CharField(max_length=20)),
                ('apellido_m_cotitular', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 2, 34, 23, 650315)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 2, 34, 23, 665945)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 2, 34, 23, 650315)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 2, 34, 23, 650315)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 2, 34, 23, 650315)),
        ),
        migrations.CreateModel(
            name='Det_Boleto_Empeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('avaluo', models.IntegerField()),
                ('mutuo_sugerido', models.IntegerField()),
                ('mutuo', models.IntegerField()),
                ('boleta_empeno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Boleta_Empeno')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Linea')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Marca')),
                ('sub_linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Sub_Linea')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Tipo_Producto')),
            ],
        ),
        migrations.AddField(
            model_name='boleta_empeno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Cliente'),
        ),
        migrations.AddField(
            model_name='boleta_empeno',
            name='plazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Plazo'),
        ),
        migrations.AddField(
            model_name='boleta_empeno',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Tipo_Producto'),
        ),
        migrations.AddField(
            model_name='boleta_empeno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
