# Generated by Django 2.2.6 on 2020-07-05 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0047_auto_20200705_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta_empeno',
            name='estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empenos.Estatus_Boleta'),
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 10, 36, 16, 410455)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 10, 36, 16, 258915)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 10, 36, 16, 359892)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 10, 36, 16, 263487)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 10, 36, 16, 263487)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 10, 36, 16, 269027)),
        ),
    ]
