# Generated by Django 2.2.6 on 2020-07-06 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0051_auto_20200705_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 13, 7, 18, 184492)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 13, 7, 18, 146483)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 13, 7, 18, 164489)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_interior',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 13, 7, 18, 148483)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 13, 7, 18, 150483)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 13, 7, 18, 153486)),
        ),
    ]
