# Generated by Django 2.2.6 on 2020-07-06 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0057_auto_20200706_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta_empeno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 17, 40, 31, 586838)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 17, 40, 31, 566831)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 17, 40, 31, 583834)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 17, 40, 31, 569827)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 17, 40, 31, 571833)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 17, 40, 31, 572830)),
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateTimeField()),
                ('importe', models.IntegerField()),
                ('pagado', models.CharField(default='N', max_length=1)),
                ('boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='empenos.Boleta_Empeno')),
                ('tipo_pago', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='empenos.Tipo_Pago')),
            ],
        ),
    ]
