# Generated by Django 2.2.6 on 2020-07-08 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0062_auto_20200707_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='det_boleto_empeno',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='empenos_temporal',
            name='marca',
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 21, 16, 4562)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 21, 15, 984425)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 21, 15, 999555)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 21, 15, 989466)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 21, 15, 989466)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 21, 15, 989466)),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
