# Generated by Django 2.2.6 on 2020-07-13 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0066_auto_20200712_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='numero',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='numero_exterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='numero_interior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='apellido_m_cotitular',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='apellido_p_cotitular',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 49, 17, 728712)),
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='nombre_cotitular',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 49, 17, 701704)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_m',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='calle',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 49, 17, 725712)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_exterior',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_fijo',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 49, 17, 705708)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 49, 17, 709711)),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='calle',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='colonia',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 49, 17, 711710)),
        ),
    ]
