# Generated by Django 2.2.6 on 2020-07-13 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0067_auto_20200713_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta_empeno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 54, 7, 548273)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 54, 7, 527266)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 54, 7, 544274)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 54, 7, 532266)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 54, 7, 534269)),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='calle',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='colonia',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='numero_exterior',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='numero_interior',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='pais',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 54, 7, 535270)),
        ),
    ]
