# Generated by Django 2.2.6 on 2020-08-04 16:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empenos', '0075_auto_20200720_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 8, 4, 16, 35, 50, 467841))),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 16, 35, 50, 453837)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 16, 35, 50, 431829)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 16, 35, 50, 450834)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 16, 35, 50, 434831)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 16, 35, 50, 436831)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 16, 35, 50, 438832)),
        ),
        migrations.CreateModel(
            name='Rel_Abono_Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Abono')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Pagos')),
            ],
        ),
    ]
