# Generated by Django 2.2.6 on 2020-07-28 19:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0076_auto_20200804_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 19, 0, 44, 294934)),
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 19, 0, 44, 282934)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 19, 0, 44, 263927)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 19, 0, 44, 279930)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 19, 0, 44, 266928)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 19, 0, 44, 267927)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 19, 0, 44, 270929)),
        ),
        migrations.CreateModel(
            name='Rel_Abono_Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('capital_restante', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('abono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Abono')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Boleta_Empeno')),
            ],
        ),
    ]
