# Generated by Django 2.2.6 on 2020-07-23 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0078_auto_20200731_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta_empeno',
            name='mutuo_original',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 46, 20, 791768)),
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 46, 20, 771760)),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 46, 20, 749754)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 46, 20, 769758)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 46, 20, 753755)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 46, 20, 755754)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 12, 46, 20, 761760)),
        ),
    ]
