# Generated by Django 2.2.6 on 2020-07-26 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0079_auto_20200723_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 20, 24, 24, 391547)),
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 20, 24, 24, 339501)),
        ),
        migrations.AlterField(
            model_name='boleta_empeno',
            name='folio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 20, 24, 24, 247437)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 20, 24, 24, 336501)),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 20, 24, 24, 274969)),
        ),
        migrations.AlterField(
            model_name='retiro_efectivo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 20, 24, 24, 277970)),
        ),
        migrations.AlterField(
            model_name='token',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 20, 24, 24, 279969)),
        ),
        migrations.AlterUniqueTogether(
            name='boleta_empeno',
            unique_together={('folio', 'sucursal')},
        ),
    ]
