# Generated by Django 2.2.6 on 2020-07-30 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empenos', '0081_auto_20200726_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imprime_Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Abono')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
