# Generated by Django 2.2.6 on 2020-07-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0082_imprime_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empenos.Cliente'),
        ),
    ]
