# Generated by Django 2.2.6 on 2020-07-30 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0083_abono_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='cliente',
        ),
        migrations.AddField(
            model_name='abono',
            name='boleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empenos.Boleta_Empeno'),
        ),
    ]
