# Generated by Django 2.2.6 on 2020-07-31 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0085_auto_20200731_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_periodo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateTimeField()),
                ('importe', models.IntegerField()),
                ('boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='empenos.Boleta_Empeno')),
                ('tipo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Tipo_Periodo')),
            ],
        ),
    ]
