# Generated by Django 2.2.6 on 2020-07-31 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0086_periodo_tipo_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empenos.Pagos'),
        ),
    ]
