# Generated by Django 2.2.6 on 2020-08-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0087_periodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='pagado',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='periodo',
            name='vencido',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
