# Generated by Django 2.2.6 on 2020-08-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0088_auto_20200802_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta_empeno',
            name='refrendo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
