# Generated by Django 2.2.6 on 2020-08-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0089_auto_20200802_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='consecutivo',
            field=models.IntegerField(default=0),
        ),
    ]
