# Generated by Django 2.2.6 on 2020-09-05 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empenos', '0090_periodo_consecutivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo_Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('vencido', models.CharField(default='N', max_length=1)),
                ('pagado', models.CharField(default='N', max_length=1)),
                ('boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='empenos.Boleta_Empeno')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empenos.Pagos')),
                ('tipo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Tipo_Periodo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
