# Generated by Django 2.2.6 on 2020-08-04 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0091_periodo_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rel_Abono_Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Abono')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.Periodo')),
            ],
        ),
    ]
