# Generated by Django 2.1.2 on 2019-03-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen_blog',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
