# Generated by Django 2.1.2 on 2019-03-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190305_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rel_Blog_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_rel', to='blog.Blog')),
                ('id_blog_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_relacionado', to='blog.Blog')),
            ],
        ),
    ]
