# Generated by Django 2.1.2 on 2019-03-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rel_blog_blog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rel_blog_blog',
            unique_together={('id_blog', 'id_blog_relacionado')},
        ),
    ]
