# Generated by Django 2.1.2 on 2019-03-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190309_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_blog', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contenido_blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='puesto_autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rel_blog_blog',
            name='id_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_blog', to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='rel_blog_blog',
            name='id_blog_relacionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_blog_relacionado', to='blog.Blog'),
        ),
        migrations.AddField(
            model_name='contenidoblog',
            name='id_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_contenido', to='blog.Blog'),
        ),
    ]
