# Generated by Django 2.2.6 on 2020-01-12 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0042_auto_20200112_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto_Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_concepto_gasto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Concepto_Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_concepto_ingreso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movs_Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fecha', models.DateField()),
                ('id_concepto_ingreso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.Concepto_Ingreso')),
                ('id_venta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ventas.Venta')),
            ],
        ),
        migrations.CreateModel(
            name='Movs_Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fecha', models.DateField()),
                ('id_concepto_Gasto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.Concepto_Gasto')),
                ('id_venta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ventas.Venta')),
            ],
        ),
    ]
