# Generated by Django 2.2.6 on 2020-01-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_auto_20200112_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aux_Reporte_Gasto_Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=100)),
                ('c2', models.CharField(max_length=100)),
                ('c3', models.CharField(max_length=100)),
                ('c4', models.CharField(max_length=100)),
                ('c5', models.CharField(max_length=100)),
            ],
        ),
    ]
