# Generated by Django 2.2.6 on 2020-01-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_aux_reporte_gasto_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aux_reporte_gasto_ingreso',
            name='c1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aux_reporte_gasto_ingreso',
            name='c2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aux_reporte_gasto_ingreso',
            name='c3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aux_reporte_gasto_ingreso',
            name='c4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aux_reporte_gasto_ingreso',
            name='c5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
