# Generated by Django 2.2.6 on 2020-01-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_auto_20200112_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aux_reporte_gasto_ingreso',
            name='c1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aux_reporte_gasto_ingreso',
            name='c2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aux_reporte_gasto_ingreso',
            name='c3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aux_reporte_gasto_ingreso',
            name='c4',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aux_reporte_gasto_ingreso',
            name='c5',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movs_gasto',
            name='id_v',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.Venta'),
        ),
        migrations.AlterField(
            model_name='movs_ingreso',
            name='id_v',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.Venta'),
        ),
    ]
