# Generated by Django 2.2.6 on 2020-01-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_auto_20200113_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movs_gasto',
            old_name='id_concepto_Gasto',
            new_name='id_concepto_gasto',
        ),
    ]
