# Generated by Django 2.2.6 on 2020-01-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_auto_20200117_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movs_gasto',
            name='id_concepto_gasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.Concepto_Gasto'),
        ),
        migrations.AlterField(
            model_name='movs_ingreso',
            name='id_concepto_ingreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.Concepto_Ingreso'),
        ),
    ]
