# Generated by Django 3.1 on 2020-08-06 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('e_mail', models.CharField(max_length=50, unique=True)),
                ('rfc', models.CharField(max_length=13, null=True)),
                ('psw', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion_Envio_Cliente_Temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('e_mail', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=13, null=True)),
                ('calle', models.CharField(max_length=50)),
                ('numero_interior', models.CharField(max_length=10, null=True)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('cp', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=50, null=True)),
                ('municipio', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='', max_length=50)),
                ('pais', models.CharField(default='', max_length=50)),
                ('referencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='E_Mail_Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recupera_pws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=18)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion_Envio_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero_interior', models.CharField(max_length=10)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('cp', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=50, null=True)),
                ('municipio', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='', max_length=50)),
                ('pais', models.CharField(default='', max_length=50)),
                ('referencia', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes_Logueados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=18)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguridad.cliente')),
            ],
        ),
    ]
