# Generated by Django 2.1.2 on 2019-04-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_cliente_psw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes_Logueados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=18)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguridad.Cliente')),
            ],
        ),
    ]
