# Generated by Django 2.1.2 on 2019-05-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_clientes_logueados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion_Envio_Cliente_Temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('e_mail', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=13)),
                ('calle', models.CharField(max_length=50)),
                ('numero_interior', models.CharField(max_length=10)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('cp', models.CharField(max_length=10)),
                ('municipio', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='', max_length=50)),
                ('pais', models.CharField(default='', max_length=50)),
                ('referencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('e_mail', 'psw')},
        ),
    ]
