# Generated by Django 2.1.2 on 2019-05-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_auto_20190525_2329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set(),
        ),
    ]
