# Generated by Django 2.1.2 on 2019-05-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_auto_20190525_2331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('e_mail', 'psw')},
        ),
    ]
