# Generated by Django 2.1.2 on 2019-05-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_auto_20190525_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='e_mail',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set(),
        ),
    ]
