# Generated by Django 2.1.2 on 2019-05-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_auto_20190525_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='direccion_envio_cliente_temporal',
            name='rfc',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
