# Generated by Django 2.1.2 on 2019-06-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_auto_20190526_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_Mail_Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=50)),
            ],
        ),
    ]
