# Generated by Django 2.2.6 on 2019-11-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0012_auto_20191113_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion_envio_cliente_temporal',
            name='apellido_m',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
