# Generated by Django 2.2.6 on 2019-11-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0013_auto_20191113_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion_envio_cliente',
            name='colonia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='direccion_envio_cliente_temporal',
            name='colonia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
