# Generated by Django 2.2.6 on 2020-01-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0014_auto_20191126_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion_envio_cliente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.Cliente'),
        ),
    ]
